### ISSUE TITLE
ImportError: No module named 'dl_layers'

### ISSUE THREAD

**Issue by Colanim** [GauravBh1010tt/DeepLearn#20]
I successfully imported `dl_text`. 

However, in `MaLSTM (Siamese)/model_Siam_LSTM.py`, there is this import statement :
`from dl_layers.layers import Abs, Exp`

and the error I received is :
`Traceback (most recent call last):
  File "main.py", line 10, in <module>
    import model_Siam_LSTM as model
  File "/home/remondn/workspace/benchmark/DeepLearn/MaLSTM (Siamese)/model_Siam_LSTM.py", line 13, in <module>
    from dl_layers.layers import Abs, Exp
ImportError: No module named 'dl_layers'`

Where can I find `dl_layers` ?

**Comment by GauravBh1010tt** [comment]
All the dependencies are defined in the [_deeplearn_utils](https://github.com/GauravBh1010tt/DeepLearn/tree/master/_deeplearn_utils) folder which can be found in the home directory.
